// TACO (Tabela Brasileira de Composição de Alimentos) Foods
// Data based on official Brazilian food composition tables

export interface AlimentoV2Insert {
  nome: string;
  categoria: string;
  subcategoria?: string;
  peso_referencia_g: number;
  medida_padrao_referencia: string;
  kcal_por_referencia: number;
  ptn_g_por_referencia: number;
  cho_g_por_referencia: number;
  lip_g_por_referencia: number;
  fibra_g_por_referencia?: number;
  sodio_mg_por_referencia?: number;
  keywords?: string[];
  tipo_refeicao_sugerida?: string[];
  descricao_curta?: string;
  preparo_sugerido?: string;
  popularidade?: number;
  fonte: string;
  ativo: boolean;
}

// Cereais, raízes e tubérculos
function seedTacoCereals(): AlimentoV2Insert[] {
  return [
    {
      nome: 'Arroz branco cozido',
      categoria: 'Cereais e derivados',
      subcategoria: 'Arroz',
      peso_referencia_g: 100,
      medida_padrao_referencia: '2 colheres de sopa',
      kcal_por_referencia: 128,
      ptn_g_por_referencia: 2.5,
      cho_g_por_referencia: 28.1,
      lip_g_por_referencia: 0.2,
      fibra_g_por_referencia: 1.6,
      sodio_mg_por_referencia: 1,
      keywords: ['arroz', 'cereais', 'básico'],
      tipo_refeicao_sugerida: ['lunch', 'dinner'],
      descricao_curta: 'Arroz branco cozido sem sal',
      preparo_sugerido: 'Cozido',
      popularidade: 100,
      fonte: 'TACO',
      ativo: true
    },
    {
      nome: 'Arroz integral cozido',
      categoria: 'Cereais e derivados',
      subcategoria: 'Arroz',
      peso_referencia_g: 100,
      medida_padrao_referencia: '2 colheres de sopa',
      kcal_por_referencia: 124,
      ptn_g_por_referencia: 2.6,
      cho_g_por_referencia: 25.8,
      lip_g_por_referencia: 1.0,
      fibra_g_por_referencia: 2.7,
      sodio_mg_por_referencia: 1,
      keywords: ['arroz', 'integral', 'fibra'],
      tipo_refeicao_sugerida: ['lunch', 'dinner'],
      descricao_curta: 'Arroz integral cozido sem sal',
      preparo_sugerido: 'Cozido',
      popularidade: 90,
      fonte: 'TACO',
      ativo: true
    },
    {
      nome: 'Macarrão cozido',
      categoria: 'Cereais e derivados',
      subcategoria: 'Massas',
      peso_referencia_g: 100,
      medida_padrao_referencia: '1 pegador',
      kcal_por_referencia: 127,
      ptn_g_por_referencia: 4.3,
      cho_g_por_referencia: 25.2,
      lip_g_por_referencia: 0.7,
      fibra_g_por_referencia: 1.6,
      sodio_mg_por_referencia: 1,
      keywords: ['macarrão', 'massa', 'carboidrato'],
      tipo_refeicao_sugerida: ['lunch', 'dinner'],
      descricao_curta: 'Macarrão sem ovos cozido',
      preparo_sugerido: 'Cozido',
      popularidade: 85,
      fonte: 'TACO',
      ativo: true
    },
    {
      nome: 'Pão francês',
      categoria: 'Cereais e derivados',
      subcategoria: 'Pães',
      peso_referencia_g: 50,
      medida_padrao_referencia: '1 unidade',
      kcal_por_referencia: 150,
      ptn_g_por_referencia: 4.8,
      cho_g_por_referencia: 29.3,
      lip_g_por_referencia: 1.5,
      fibra_g_por_referencia: 1.2,
      sodio_mg_por_referencia: 324,
      keywords: ['pão', 'francês', 'padaria'],
      tipo_refeicao_sugerida: ['breakfast', 'morning_snack'],
      descricao_curta: 'Pão francês tradicional',
      preparo_sugerido: 'Assado',
      popularidade: 95,
      fonte: 'TACO',
      ativo: true
    },
    {
      nome: 'Pão de forma integral',
      categoria: 'Cereais e derivados',
      subcategoria: 'Pães',
      peso_referencia_g: 25,
      medida_padrao_referencia: '1 fatia',
      kcal_por_referencia: 62,
      ptn_g_por_referencia: 2.3,
      cho_g_por_referencia: 11.0,
      lip_g_por_referencia: 1.1,
      fibra_g_por_referencia: 1.9,
      sodio_mg_por_referencia: 145,
      keywords: ['pão', 'integral', 'fibra'],
      tipo_refeicao_sugerida: ['breakfast', 'morning_snack'],
      descricao_curta: 'Pão de forma integral',
      preparo_sugerido: 'Pronto para consumo',
      popularidade: 80,
      fonte: 'TACO',
      ativo: true
    },
    {
      nome: 'Batata inglesa cozida',
      categoria: 'Cereais e derivados',
      subcategoria: 'Tubérculos',
      peso_referencia_g: 100,
      medida_padrao_referencia: '1 unidade média',
      kcal_por_referencia: 52,
      ptn_g_por_referencia: 1.2,
      cho_g_por_referencia: 11.9,
      lip_g_por_referencia: 0.1,
      fibra_g_por_referencia: 1.3,
      sodio_mg_por_referencia: 1,
      keywords: ['batata', 'tubérculo', 'carboidrato'],
      tipo_refeicao_sugerida: ['lunch', 'dinner'],
      descricao_curta: 'Batata inglesa cozida sem sal',
      preparo_sugerido: 'Cozida',
      popularidade: 90,
      fonte: 'TACO',
      ativo: true
    },
    {
      nome: 'Batata doce cozida',
      categoria: 'Cereais e derivados',
      subcategoria: 'Tubérculos',
      peso_referencia_g: 100,
      medida_padrao_referencia: '1 unidade média',
      kcal_por_referencia: 77,
      ptn_g_por_referencia: 0.6,
      cho_g_por_referencia: 18.4,
      lip_g_por_referencia: 0.1,
      fibra_g_por_referencia: 2.2,
      sodio_mg_por_referencia: 9,
      keywords: ['batata doce', 'tubérculo', 'fitness'],
      tipo_refeicao_sugerida: ['lunch', 'dinner', 'afternoon_snack'],
      descricao_curta: 'Batata doce cozida',
      preparo_sugerido: 'Cozida',
      popularidade: 85,
      fonte: 'TACO',
      ativo: true
    },
    {
      nome: 'Mandioca cozida',
      categoria: 'Cereais e derivados',
      subcategoria: 'Tubérculos',
      peso_referencia_g: 100,
      medida_padrao_referencia: '1 pedaço médio',
      kcal_por_referencia: 125,
      ptn_g_por_referencia: 0.6,
      cho_g_por_referencia: 30.1,
      lip_g_por_referencia: 0.3,
      fibra_g_por_referencia: 1.6,
      sodio_mg_por_referencia: 1,
      keywords: ['mandioca', 'aipim', 'macaxeira'],
      tipo_refeicao_sugerida: ['lunch', 'dinner'],
      descricao_curta: 'Mandioca cozida (aipim/macaxeira)',
      preparo_sugerido: 'Cozida',
      popularidade: 75,
      fonte: 'TACO',
      ativo: true
    },
    {
      nome: 'Aveia em flocos',
      categoria: 'Cereais e derivados',
      subcategoria: 'Cereais matinais',
      peso_referencia_g: 30,
      medida_padrao_referencia: '3 colheres de sopa',
      kcal_por_referencia: 117,
      ptn_g_por_referencia: 4.2,
      cho_g_por_referencia: 19.8,
      lip_g_por_referencia: 2.3,
      fibra_g_por_referencia: 2.7,
      sodio_mg_por_referencia: 1,
      keywords: ['aveia', 'cereal', 'fibra', 'fitness'],
      tipo_refeicao_sugerida: ['breakfast', 'morning_snack'],
      descricao_curta: 'Aveia em flocos',
      preparo_sugerido: 'Pode ser consumida crua ou cozida',
      popularidade: 88,
      fonte: 'TACO',
      ativo: true
    },
    {
      nome: 'Tapioca',
      categoria: 'Cereais e derivados',
      subcategoria: 'Farinhas',
      peso_referencia_g: 50,
      medida_padrao_referencia: '1 unidade',
      kcal_por_referencia: 174,
      ptn_g_por_referencia: 0.1,
      cho_g_por_referencia: 43.0,
      lip_g_por_referencia: 0.0,
      fibra_g_por_referencia: 0.2,
      sodio_mg_por_referencia: 0,
      keywords: ['tapioca', 'goma', 'regional'],
      tipo_refeicao_sugerida: ['breakfast', 'afternoon_snack'],
      descricao_curta: 'Tapioca (goma de mandioca)',
      preparo_sugerido: 'Hidratada e aquecida em frigideira',
      popularidade: 70,
      fonte: 'TACO',
      ativo: true
    }
  ];
}

// Leguminosas
function seedTacoLegumes(): AlimentoV2Insert[] {
  return [
    {
      nome: 'Feijão preto cozido',
      categoria: 'Leguminosas',
      subcategoria: 'Feijões',
      peso_referencia_g: 100,
      medida_padrao_referencia: '1 concha pequena',
      kcal_por_referencia: 77,
      ptn_g_por_referencia: 4.5,
      cho_g_por_referencia: 14.0,
      lip_g_por_referencia: 0.5,
      fibra_g_por_referencia: 8.4,
      sodio_mg_por_referencia: 2,
      keywords: ['feijão', 'proteína', 'fibra'],
      tipo_refeicao_sugerida: ['lunch', 'dinner'],
      descricao_curta: 'Feijão preto cozido sem sal',
      preparo_sugerido: 'Cozido',
      popularidade: 100,
      fonte: 'TACO',
      ativo: true
    },
    {
      nome: 'Feijão carioca cozido',
      categoria: 'Leguminosas',
      subcategoria: 'Feijões',
      peso_referencia_g: 100,
      medida_padrao_referencia: '1 concha pequena',
      kcal_por_referencia: 76,
      ptn_g_por_referencia: 4.8,
      cho_g_por_referencia: 13.6,
      lip_g_por_referencia: 0.5,
      fibra_g_por_referencia: 8.5,
      sodio_mg_por_referencia: 2,
      keywords: ['feijão', 'proteína', 'fibra'],
      tipo_refeicao_sugerida: ['lunch', 'dinner'],
      descricao_curta: 'Feijão carioca cozido sem sal',
      preparo_sugerido: 'Cozido',
      popularidade: 100,
      fonte: 'TACO',
      ativo: true
    },
    {
      nome: 'Lentilha cozida',
      categoria: 'Leguminosas',
      subcategoria: 'Outros',
      peso_referencia_g: 100,
      medida_padrao_referencia: '1 concha pequena',
      kcal_por_referencia: 93,
      ptn_g_por_referencia: 6.3,
      cho_g_por_referencia: 16.3,
      lip_g_por_referencia: 0.5,
      fibra_g_por_referencia: 7.9,
      sodio_mg_por_referencia: 2,
      keywords: ['lentilha', 'proteína', 'ferro'],
      tipo_refeicao_sugerida: ['lunch', 'dinner'],
      descricao_curta: 'Lentilha cozida',
      preparo_sugerido: 'Cozida',
      popularidade: 70,
      fonte: 'TACO',
      ativo: true
    },
    {
      nome: 'Grão de bico cozido',
      categoria: 'Leguminosas',
      subcategoria: 'Outros',
      peso_referencia_g: 100,
      medida_padrao_referencia: '3 colheres de sopa',
      kcal_por_referencia: 121,
      ptn_g_por_referencia: 6.5,
      cho_g_por_referencia: 19.3,
      lip_g_por_referencia: 2.0,
      fibra_g_por_referencia: 5.4,
      sodio_mg_por_referencia: 3,
      keywords: ['grão de bico', 'proteína', 'mediterrâneo'],
      tipo_refeicao_sugerida: ['lunch', 'dinner'],
      descricao_curta: 'Grão de bico cozido',
      preparo_sugerido: 'Cozido',
      popularidade: 75,
      fonte: 'TACO',
      ativo: true
    },
    {
      nome: 'Ervilha verde cozida',
      categoria: 'Leguminosas',
      subcategoria: 'Outros',
      peso_referencia_g: 100,
      medida_padrao_referencia: '3 colheres de sopa',
      kcal_por_referencia: 63,
      ptn_g_por_referencia: 4.8,
      cho_g_por_referencia: 10.0,
      lip_g_por_referencia: 0.2,
      fibra_g_por_referencia: 4.2,
      sodio_mg_por_referencia: 1,
      keywords: ['ervilha', 'proteína', 'verde'],
      tipo_refeicao_sugerida: ['lunch', 'dinner'],
      descricao_curta: 'Ervilha verde cozida',
      preparo_sugerido: 'Cozida',
      popularidade: 65,
      fonte: 'TACO',
      ativo: true
    },
    {
      nome: 'Soja cozida',
      categoria: 'Leguminosas',
      subcategoria: 'Soja e derivados',
      peso_referencia_g: 100,
      medida_padrao_referencia: '3 colheres de sopa',
      kcal_por_referencia: 128,
      ptn_g_por_referencia: 11.9,
      cho_g_por_referencia: 9.9,
      lip_g_por_referencia: 5.0,
      fibra_g_por_referencia: 4.2,
      sodio_mg_por_referencia: 1,
      keywords: ['soja', 'proteína', 'vegetariano'],
      tipo_refeicao_sugerida: ['lunch', 'dinner'],
      descricao_curta: 'Soja em grão cozida',
      preparo_sugerido: 'Cozida',
      popularidade: 60,
      fonte: 'TACO',
      ativo: true
    }
  ];
}

// Vegetais
function seedTacoVegetables(): AlimentoV2Insert[] {
  return [
    {
      nome: 'Alface crespa',
      categoria: 'Vegetais',
      subcategoria: 'Folhas',
      peso_referencia_g: 50,
      medida_padrao_referencia: '3 folhas',
      kcal_por_referencia: 7,
      ptn_g_por_referencia: 0.7,
      cho_g_por_referencia: 1.3,
      lip_g_por_referencia: 0.1,
      fibra_g_por_referencia: 1.0,
      sodio_mg_por_referencia: 12,
      keywords: ['alface', 'salada', 'folha'],
      tipo_refeicao_sugerida: ['lunch', 'dinner'],
      descricao_curta: 'Alface crespa crua',
      preparo_sugerido: 'Crua',
      popularidade: 95,
      fonte: 'TACO',
      ativo: true
    },
    {
      nome: 'Tomate',
      categoria: 'Vegetais',
      subcategoria: 'Frutos',
      peso_referencia_g: 100,
      medida_padrao_referencia: '1 unidade média',
      kcal_por_referencia: 15,
      ptn_g_por_referencia: 1.1,
      cho_g_por_referencia: 3.1,
      lip_g_por_referencia: 0.2,
      fibra_g_por_referencia: 1.2,
      sodio_mg_por_referencia: 4,
      keywords: ['tomate', 'salada', 'licopeno'],
      tipo_refeicao_sugerida: ['lunch', 'dinner'],
      descricao_curta: 'Tomate cru',
      preparo_sugerido: 'Cru',
      popularidade: 95,
      fonte: 'TACO',
      ativo: true
    },
    {
      nome: 'Cenoura crua',
      categoria: 'Vegetais',
      subcategoria: 'Raízes',
      peso_referencia_g: 100,
      medida_padrao_referencia: '1 unidade média',
      kcal_por_referencia: 34,
      ptn_g_por_referencia: 1.3,
      cho_g_por_referencia: 7.7,
      lip_g_por_referencia: 0.2,
      fibra_g_por_referencia: 3.2,
      sodio_mg_por_referencia: 32,
      keywords: ['cenoura', 'beta-caroteno', 'vitamina A'],
      tipo_refeicao_sugerida: ['lunch', 'dinner', 'afternoon_snack'],
      descricao_curta: 'Cenoura crua',
      preparo_sugerido: 'Crua ou cozida',
      popularidade: 90,
      fonte: 'TACO',
      ativo: true
    },
    {
      nome: 'Brócolis cozido',
      categoria: 'Vegetais',
      subcategoria: 'Crucíferos',
      peso_referencia_g: 100,
      medida_padrao_referencia: '2 colheres de sopa',
      kcal_por_referencia: 25,
      ptn_g_por_referencia: 2.9,
      cho_g_por_referencia: 4.0,
      lip_g_por_referencia: 0.4,
      fibra_g_por_referencia: 2.9,
      sodio_mg_por_referencia: 9,
      keywords: ['brócolis', 'crucífero', 'anti-câncer'],
      tipo_refeicao_sugerida: ['lunch', 'dinner'],
      descricao_curta: 'Brócolis cozido',
      preparo_sugerido: 'Cozido no vapor',
      popularidade: 80,
      fonte: 'TACO',
      ativo: true
    },
    {
      nome: 'Couve manteiga refogada',
      categoria: 'Vegetais',
      subcategoria: 'Folhas',
      peso_referencia_g: 100,
      medida_padrao_referencia: '2 colheres de sopa',
      kcal_por_referencia: 36,
      ptn_g_por_referencia: 3.4,
      cho_g_por_referencia: 5.7,
      lip_g_por_referencia: 0.5,
      fibra_g_por_referencia: 3.1,
      sodio_mg_por_referencia: 6,
      keywords: ['couve', 'folha', 'ferro', 'cálcio'],
      tipo_refeicao_sugerida: ['lunch', 'dinner'],
      descricao_curta: 'Couve manteiga refogada',
      preparo_sugerido: 'Refogada',
      popularidade: 85,
      fonte: 'TACO',
      ativo: true
    },
    {
      nome: 'Abóbora cozida',
      categoria: 'Vegetais',
      subcategoria: 'Frutos',
      peso_referencia_g: 100,
      medida_padrao_referencia: '2 colheres de sopa',
      kcal_por_referencia: 29,
      ptn_g_por_referencia: 1.0,
      cho_g_por_referencia: 6.9,
      lip_g_por_referencia: 0.1,
      fibra_g_por_referencia: 1.9,
      sodio_mg_por_referencia: 1,
      keywords: ['abóbora', 'beta-caroteno', 'doce'],
      tipo_refeicao_sugerida: ['lunch', 'dinner'],
      descricao_curta: 'Abóbora cozida',
      preparo_sugerido: 'Cozida',
      popularidade: 75,
      fonte: 'TACO',
      ativo: true
    },
    {
      nome: 'Chuchu cozido',
      categoria: 'Vegetais',
      subcategoria: 'Frutos',
      peso_referencia_g: 100,
      medida_padrao_referencia: '2 colheres de sopa',
      kcal_por_referencia: 18,
      ptn_g_por_referencia: 0.8,
      cho_g_por_referencia: 4.2,
      lip_g_por_referencia: 0.1,
      fibra_g_por_referencia: 0.9,
      sodio_mg_por_referencia: 1,
      keywords: ['chuchu', 'baixa caloria'],
      tipo_refeicao_sugerida: ['lunch', 'dinner'],
      descricao_curta: 'Chuchu cozido',
      preparo_sugerido: 'Cozido',
      popularidade: 70,
      fonte: 'TACO',
      ativo: true
    },
    {
      nome: 'Berinjela cozida',
      categoria: 'Vegetais',
      subcategoria: 'Frutos',
      peso_referencia_g: 100,
      medida_padrao_referencia: '3 fatias',
      kcal_por_referencia: 20,
      ptn_g_por_referencia: 0.8,
      cho_g_por_referencia: 4.5,
      lip_g_por_referencia: 0.1,
      fibra_g_por_referencia: 2.5,
      sodio_mg_por_referencia: 1,
      keywords: ['berinjela', 'roxo', 'mediterrâneo'],
      tipo_refeicao_sugerida: ['lunch', 'dinner'],
      descricao_curta: 'Berinjela cozida',
      preparo_sugerido: 'Cozida ou assada',
      popularidade: 65,
      fonte: 'TACO',
      ativo: true
    },
    {
      nome: 'Pepino',
      categoria: 'Vegetais',
      subcategoria: 'Frutos',
      peso_referencia_g: 100,
      medida_padrao_referencia: '½ unidade',
      kcal_por_referencia: 12,
      ptn_g_por_referencia: 0.9,
      cho_g_por_referencia: 2.3,
      lip_g_por_referencia: 0.2,
      fibra_g_por_referencia: 0.5,
      sodio_mg_por_referencia: 2,
      keywords: ['pepino', 'hidratação', 'salada'],
      tipo_refeicao_sugerida: ['lunch', 'dinner'],
      descricao_curta: 'Pepino cru',
      preparo_sugerido: 'Cru',
      popularidade: 85,
      fonte: 'TACO',
      ativo: true
    },
    {
      nome: 'Beterraba cozida',
      categoria: 'Vegetais',
      subcategoria: 'Raízes',
      peso_referencia_g: 100,
      medida_padrao_referencia: '3 fatias',
      kcal_por_referencia: 32,
      ptn_g_por_referencia: 1.3,
      cho_g_por_referencia: 7.2,
      lip_g_por_referencia: 0.1,
      fibra_g_por_referencia: 2.6,
      sodio_mg_por_referencia: 38,
      keywords: ['beterraba', 'ferro', 'antioxidante'],
      tipo_refeicao_sugerida: ['lunch', 'dinner'],
      descricao_curta: 'Beterraba cozida',
      preparo_sugerido: 'Cozida',
      popularidade: 75,
      fonte: 'TACO',
      ativo: true
    }
  ];
}

// Frutas
function seedTacoFruits(): AlimentoV2Insert[] {
  return [
    {
      nome: 'Banana prata',
      categoria: 'Frutas',
      subcategoria: 'Frutas in natura',
      peso_referencia_g: 100,
      medida_padrao_referencia: '1 unidade média',
      kcal_por_referencia: 98,
      ptn_g_por_referencia: 1.3,
      cho_g_por_referencia: 26.0,
      lip_g_por_referencia: 0.1,
      fibra_g_por_referencia: 2.0,
      sodio_mg_por_referencia: 2,
      keywords: ['banana', 'potássio', 'energia'],
      tipo_refeicao_sugerida: ['breakfast', 'morning_snack', 'afternoon_snack'],
      descricao_curta: 'Banana prata',
      preparo_sugerido: 'In natura',
      popularidade: 100,
      fonte: 'TACO',
      ativo: true
    },
    {
      nome: 'Maçã',
      categoria: 'Frutas',
      subcategoria: 'Frutas in natura',
      peso_referencia_g: 100,
      medida_padrao_referencia: '1 unidade média',
      kcal_por_referencia: 56,
      ptn_g_por_referencia: 0.3,
      cho_g_por_referencia: 15.2,
      lip_g_por_referencia: 0.0,
      fibra_g_por_referencia: 1.3,
      sodio_mg_por_referencia: 0,
      keywords: ['maçã', 'fibra', 'lanche'],
      tipo_refeicao_sugerida: ['breakfast', 'morning_snack', 'afternoon_snack'],
      descricao_curta: 'Maçã com casca',
      preparo_sugerido: 'In natura',
      popularidade: 95,
      fonte: 'TACO',
      ativo: true
    },
    {
      nome: 'Laranja pera',
      categoria: 'Frutas',
      subcategoria: 'Frutas in natura',
      peso_referencia_g: 100,
      medida_padrao_referencia: '1 unidade média',
      kcal_por_referencia: 46,
      ptn_g_por_referencia: 0.9,
      cho_g_por_referencia: 11.5,
      lip_g_por_referencia: 0.1,
      fibra_g_por_referencia: 1.1,
      sodio_mg_por_referencia: 0,
      keywords: ['laranja', 'vitamina C', 'cítrico'],
      tipo_refeicao_sugerida: ['breakfast', 'morning_snack', 'afternoon_snack'],
      descricao_curta: 'Laranja pera',
      preparo_sugerido: 'In natura',
      popularidade: 90,
      fonte: 'TACO',
      ativo: true
    },
    {
      nome: 'Mamão papaia',
      categoria: 'Frutas',
      subcategoria: 'Frutas in natura',
      peso_referencia_g: 100,
      medida_padrao_referencia: '½ unidade pequena',
      kcal_por_referencia: 40,
      ptn_g_por_referencia: 0.5,
      cho_g_por_referencia: 10.4,
      lip_g_por_referencia: 0.1,
      fibra_g_por_referencia: 1.0,
      sodio_mg_por_referencia: 2,
      keywords: ['mamão', 'digestão', 'fibra'],
      tipo_refeicao_sugerida: ['breakfast', 'afternoon_snack'],
      descricao_curta: 'Mamão papaia',
      preparo_sugerido: 'In natura',
      popularidade: 85,
      fonte: 'TACO',
      ativo: true
    },
    {
      nome: 'Melancia',
      categoria: 'Frutas',
      subcategoria: 'Frutas in natura',
      peso_referencia_g: 100,
      medida_padrao_referencia: '1 fatia média',
      kcal_por_referencia: 33,
      ptn_g_por_referencia: 0.9,
      cho_g_por_referencia: 8.1,
      lip_g_por_referencia: 0.0,
      fibra_g_por_referencia: 0.1,
      sodio_mg_por_referencia: 1,
      keywords: ['melancia', 'hidratação', 'verão'],
      tipo_refeicao_sugerida: ['afternoon_snack'],
      descricao_curta: 'Melancia',
      preparo_sugerido: 'In natura',
      popularidade: 85,
      fonte: 'TACO',
      ativo: true
    },
    {
      nome: 'Abacaxi',
      categoria: 'Frutas',
      subcategoria: 'Frutas in natura',
      peso_referencia_g: 100,
      medida_padrao_referencia: '1 fatia média',
      kcal_por_referencia: 48,
      ptn_g_por_referencia: 0.9,
      cho_g_por_referencia: 12.3,
      lip_g_por_referencia: 0.1,
      fibra_g_por_referencia: 1.0,
      sodio_mg_por_referencia: 1,
      keywords: ['abacaxi', 'bromelina', 'digestão'],
      tipo_refeicao_sugerida: ['afternoon_snack'],
      descricao_curta: 'Abacaxi',
      preparo_sugerido: 'In natura',
      popularidade: 80,
      fonte: 'TACO',
      ativo: true
    },
    {
      nome: 'Morango',
      categoria: 'Frutas',
      subcategoria: 'Frutas in natura',
      peso_referencia_g: 100,
      medida_padrao_referencia: '7 unidades',
      kcal_por_referencia: 30,
      ptn_g_por_referencia: 0.9,
      cho_g_por_referencia: 6.8,
      lip_g_por_referencia: 0.3,
      fibra_g_por_referencia: 1.7,
      sodio_mg_por_referencia: 1,
      keywords: ['morango', 'antioxidante', 'vitamina C'],
      tipo_refeicao_sugerida: ['breakfast', 'afternoon_snack'],
      descricao_curta: 'Morango',
      preparo_sugerido: 'In natura',
      popularidade: 85,
      fonte: 'TACO',
      ativo: true
    },
    {
      nome: 'Uva',
      categoria: 'Frutas',
      subcategoria: 'Frutas in natura',
      peso_referencia_g: 100,
      medida_padrao_referencia: '10 unidades',
      kcal_por_referencia: 69,
      ptn_g_por_referencia: 0.6,
      cho_g_por_referencia: 18.1,
      lip_g_por_referencia: 0.4,
      fibra_g_por_referencia: 0.9,
      sodio_mg_por_referencia: 2,
      keywords: ['uva', 'resveratrol', 'antioxidante'],
      tipo_refeicao_sugerida: ['afternoon_snack'],
      descricao_curta: 'Uva',
      preparo_sugerido: 'In natura',
      popularidade: 80,
      fonte: 'TACO',
      ativo: true
    },
    {
      nome: 'Manga',
      categoria: 'Frutas',
      subcategoria: 'Frutas in natura',
      peso_referencia_g: 100,
      medida_padrao_referencia: '½ unidade média',
      kcal_por_referencia: 51,
      ptn_g_por_referencia: 0.6,
      cho_g_por_referencia: 13.5,
      lip_g_por_referencia: 0.2,
      fibra_g_por_referencia: 1.6,
      sodio_mg_por_referencia: 1,
      keywords: ['manga', 'vitamina A', 'tropical'],
      tipo_refeicao_sugerida: ['afternoon_snack'],
      descricao_curta: 'Manga',
      preparo_sugerido: 'In natura',
      popularidade: 85,
      fonte: 'TACO',
      ativo: true
    },
    {
      nome: 'Goiaba',
      categoria: 'Frutas',
      subcategoria: 'Frutas in natura',
      peso_referencia_g: 100,
      medida_padrao_referencia: '1 unidade média',
      kcal_por_referencia: 54,
      ptn_g_por_referencia: 1.1,
      cho_g_por_referencia: 13.0,
      lip_g_por_referencia: 0.4,
      fibra_g_por_referencia: 6.2,
      sodio_mg_por_referencia: 1,
      keywords: ['goiaba', 'vitamina C', 'fibra'],
      tipo_refeicao_sugerida: ['afternoon_snack'],
      descricao_curta: 'Goiaba',
      preparo_sugerido: 'In natura',
      popularidade: 70,
      fonte: 'TACO',
      ativo: true
    }
  ];
}

// Proteínas (carnes, ovos, laticínios)
function seedTacoProteins(): AlimentoV2Insert[] {
  return [
    {
      nome: 'Peito de frango grelhado',
      categoria: 'Carnes e ovos',
      subcategoria: 'Aves',
      peso_referencia_g: 100,
      medida_padrao_referencia: '1 filé médio',
      kcal_por_referencia: 159,
      ptn_g_por_referencia: 32.0,
      cho_g_por_referencia: 0.0,
      lip_g_por_referencia: 3.6,
      fibra_g_por_referencia: 0.0,
      sodio_mg_por_referencia: 63,
      keywords: ['frango', 'proteína', 'magra', 'fitness'],
      tipo_refeicao_sugerida: ['lunch', 'dinner'],
      descricao_curta: 'Peito de frango sem pele grelhado',
      preparo_sugerido: 'Grelhado',
      popularidade: 100,
      fonte: 'TACO',
      ativo: true
    },
    {
      nome: 'Ovo cozido',
      categoria: 'Carnes e ovos',
      subcategoria: 'Ovos',
      peso_referencia_g: 50,
      medida_padrao_referencia: '1 unidade',
      kcal_por_referencia: 78,
      ptn_g_por_referencia: 6.5,
      cho_g_por_referencia: 0.6,
      lip_g_por_referencia: 5.3,
      fibra_g_por_referencia: 0.0,
      sodio_mg_por_referencia: 71,
      keywords: ['ovo', 'proteína', 'completa'],
      tipo_refeicao_sugerida: ['breakfast', 'lunch', 'afternoon_snack'],
      descricao_curta: 'Ovo de galinha cozido',
      preparo_sugerido: 'Cozido',
      popularidade: 100,
      fonte: 'TACO',
      ativo: true
    },
    {
      nome: 'Carne bovina magra grelhada',
      categoria: 'Carnes e ovos',
      subcategoria: 'Carnes bovinas',
      peso_referencia_g: 100,
      medida_padrao_referencia: '1 bife médio',
      kcal_por_referencia: 163,
      ptn_g_por_referencia: 28.6,
      cho_g_por_referencia: 0.0,
      lip_g_por_referencia: 5.3,
      fibra_g_por_referencia: 0.0,
      sodio_mg_por_referencia: 59,
      keywords: ['carne', 'proteína', 'ferro', 'boi'],
      tipo_refeicao_sugerida: ['lunch', 'dinner'],
      descricao_curta: 'Carne bovina magra grelhada',
      preparo_sugerido: 'Grelhado',
      popularidade: 95,
      fonte: 'TACO',
      ativo: true
    },
    {
      nome: 'Peixe tilápia grelhado',
      categoria: 'Carnes e ovos',
      subcategoria: 'Peixes',
      peso_referencia_g: 100,
      medida_padrao_referencia: '1 filé médio',
      kcal_por_referencia: 96,
      ptn_g_por_referencia: 20.1,
      cho_g_por_referencia: 0.0,
      lip_g_por_referencia: 1.7,
      fibra_g_por_referencia: 0.0,
      sodio_mg_por_referencia: 50,
      keywords: ['peixe', 'proteína', 'magra', 'ômega'],
      tipo_refeicao_sugerida: ['lunch', 'dinner'],
      descricao_curta: 'Tilápia grelhada',
      preparo_sugerido: 'Grelhado',
      popularidade: 85,
      fonte: 'TACO',
      ativo: true
    },
    {
      nome: 'Atum em lata',
      categoria: 'Carnes e ovos',
      subcategoria: 'Peixes',
      peso_referencia_g: 100,
      medida_padrao_referencia: '1 lata',
      kcal_por_referencia: 108,
      ptn_g_por_referencia: 25.0,
      cho_g_por_referencia: 0.0,
      lip_g_por_referencia: 0.8,
      fibra_g_por_referencia: 0.0,
      sodio_mg_por_referencia: 333,
      keywords: ['atum', 'proteína', 'praticidade', 'ômega 3'],
      tipo_refeicao_sugerida: ['lunch', 'dinner', 'afternoon_snack'],
      descricao_curta: 'Atum em conserva (água)',
      preparo_sugerido: 'Pronto para consumo',
      popularidade: 80,
      fonte: 'TACO',
      ativo: true
    },
    {
      nome: 'Sardinha em lata',
      categoria: 'Carnes e ovos',
      subcategoria: 'Peixes',
      peso_referencia_g: 100,
      medida_padrao_referencia: '1 lata',
      kcal_por_referencia: 130,
      ptn_g_por_referencia: 21.1,
      cho_g_por_referencia: 0.0,
      lip_g_por_referencia: 5.2,
      fibra_g_por_referencia: 0.0,
      sodio_mg_por_referencia: 505,
      keywords: ['sardinha', 'proteína', 'ômega 3', 'cálcio'],
      tipo_refeicao_sugerida: ['lunch', 'dinner'],
      descricao_curta: 'Sardinha em conserva (óleo)',
      preparo_sugerido: 'Pronto para consumo',
      popularidade: 70,
      fonte: 'TACO',
      ativo: true
    }
  ];
}

// Laticínios
function seedTacoDairy(): AlimentoV2Insert[] {
  return [
    {
      nome: 'Leite desnatado',
      categoria: 'Leite e derivados',
      subcategoria: 'Leites',
      peso_referencia_g: 200,
      medida_padrao_referencia: '1 copo',
      kcal_por_referencia: 68,
      ptn_g_por_referencia: 6.8,
      cho_g_por_referencia: 9.6,
      lip_g_por_referencia: 0.2,
      fibra_g_por_referencia: 0.0,
      sodio_mg_por_referencia: 100,
      keywords: ['leite', 'cálcio', 'desnatado', 'proteína'],
      tipo_refeicao_sugerida: ['breakfast', 'evening_snack'],
      descricao_curta: 'Leite de vaca desnatado',
      preparo_sugerido: 'Pronto para consumo',
      popularidade: 90,
      fonte: 'TACO',
      ativo: true
    },
    {
      nome: 'Iogurte natural desnatado',
      categoria: 'Leite e derivados',
      subcategoria: 'Iogurtes',
      peso_referencia_g: 100,
      medida_padrao_referencia: '1 pote',
      kcal_por_referencia: 51,
      ptn_g_por_referencia: 4.3,
      cho_g_por_referencia: 7.0,
      lip_g_por_referencia: 0.2,
      fibra_g_por_referencia: 0.0,
      sodio_mg_por_referencia: 60,
      keywords: ['iogurte', 'probiótico', 'cálcio'],
      tipo_refeicao_sugerida: ['breakfast', 'afternoon_snack'],
      descricao_curta: 'Iogurte natural desnatado',
      preparo_sugerido: 'Pronto para consumo',
      popularidade: 85,
      fonte: 'TACO',
      ativo: true
    },
    {
      nome: 'Queijo minas frescal',
      categoria: 'Leite e derivados',
      subcategoria: 'Queijos',
      peso_referencia_g: 30,
      medida_padrao_referencia: '1 fatia',
      kcal_por_referencia: 84,
      ptn_g_por_referencia: 5.3,
      cho_g_por_referencia: 1.0,
      lip_g_por_referencia: 6.8,
      fibra_g_por_referencia: 0.0,
      sodio_mg_por_referencia: 129,
      keywords: ['queijo', 'cálcio', 'proteína'],
      tipo_refeicao_sugerida: ['breakfast', 'afternoon_snack'],
      descricao_curta: 'Queijo minas frescal',
      preparo_sugerido: 'Pronto para consumo',
      popularidade: 90,
      fonte: 'TACO',
      ativo: true
    },
    {
      nome: 'Queijo cottage',
      categoria: 'Leite e derivados',
      subcategoria: 'Queijos',
      peso_referencia_g: 50,
      medida_padrao_referencia: '2 colheres de sopa',
      kcal_por_referencia: 55,
      ptn_g_por_referencia: 6.2,
      cho_g_por_referencia: 1.7,
      lip_g_por_referencia: 2.3,
      fibra_g_por_referencia: 0.0,
      sodio_mg_por_referencia: 228,
      keywords: ['queijo', 'cottage', 'proteína', 'magro'],
      tipo_refeicao_sugerida: ['breakfast', 'afternoon_snack'],
      descricao_curta: 'Queijo cottage',
      preparo_sugerido: 'Pronto para consumo',
      popularidade: 75,
      fonte: 'TACO',
      ativo: true
    },
    {
      nome: 'Requeijão cremoso light',
      categoria: 'Leite e derivados',
      subcategoria: 'Queijos',
      peso_referencia_g: 15,
      medida_padrao_referencia: '1 colher de sopa',
      kcal_por_referencia: 27,
      ptn_g_por_referencia: 1.2,
      cho_g_por_referencia: 0.8,
      lip_g_por_referencia: 2.1,
      fibra_g_por_referencia: 0.0,
      sodio_mg_por_referencia: 90,
      keywords: ['requeijão', 'light', 'cremoso'],
      tipo_refeicao_sugerida: ['breakfast'],
      descricao_curta: 'Requeijão cremoso light',
      preparo_sugerido: 'Pronto para consumo',
      popularidade: 80,
      fonte: 'TACO',
      ativo: true
    }
  ];
}

// Gorduras e óleos
function seedTacoFatsOils(): AlimentoV2Insert[] {
  return [
    {
      nome: 'Azeite de oliva extravirgem',
      categoria: 'Óleos e gorduras',
      subcategoria: 'Óleos vegetais',
      peso_referencia_g: 10,
      medida_padrao_referencia: '1 colher de sopa',
      kcal_por_referencia: 88,
      ptn_g_por_referencia: 0.0,
      cho_g_por_referencia: 0.0,
      lip_g_por_referencia: 10.0,
      fibra_g_por_referencia: 0.0,
      sodio_mg_por_referencia: 0,
      keywords: ['azeite', 'oliva', 'gordura boa', 'mediterrâneo'],
      tipo_refeicao_sugerida: ['lunch', 'dinner'],
      descricao_curta: 'Azeite de oliva extravirgem',
      preparo_sugerido: 'Tempero',
      popularidade: 95,
      fonte: 'TACO',
      ativo: true
    },
    {
      nome: 'Óleo de coco',
      categoria: 'Óleos e gorduras',
      subcategoria: 'Óleos vegetais',
      peso_referencia_g: 10,
      medida_padrao_referencia: '1 colher de sopa',
      kcal_por_referencia: 92,
      ptn_g_por_referencia: 0.0,
      cho_g_por_referencia: 0.0,
      lip_g_por_referencia: 10.2,
      fibra_g_por_referencia: 0.0,
      sodio_mg_por_referencia: 0,
      keywords: ['óleo', 'coco', 'TCM'],
      tipo_refeicao_sugerida: ['breakfast', 'lunch', 'dinner'],
      descricao_curta: 'Óleo de coco',
      preparo_sugerido: 'Para cozinhar ou temperar',
      popularidade: 70,
      fonte: 'TACO',
      ativo: true
    },
    {
      nome: 'Abacate',
      categoria: 'Óleos e gorduras',
      subcategoria: 'Frutas oleaginosas',
      peso_referencia_g: 100,
      medida_padrao_referencia: '½ unidade média',
      kcal_por_referencia: 96,
      ptn_g_por_referencia: 1.2,
      cho_g_por_referencia: 6.4,
      lip_g_por_referencia: 8.4,
      fibra_g_por_referencia: 3.4,
      sodio_mg_por_referencia: 2,
      keywords: ['abacate', 'gordura boa', 'omega 9'],
      tipo_refeicao_sugerida: ['breakfast', 'lunch', 'afternoon_snack'],
      descricao_curta: 'Abacate',
      preparo_sugerido: 'In natura',
      popularidade: 85,
      fonte: 'TACO',
      ativo: true
    }
  ];
}

// Oleaginosas
function seedTacoNutsSeeds(): AlimentoV2Insert[] {
  return [
    {
      nome: 'Castanha-do-pará',
      categoria: 'Oleaginosas',
      subcategoria: 'Castanhas',
      peso_referencia_g: 10,
      medida_padrao_referencia: '2 unidades',
      kcal_por_referencia: 70,
      ptn_g_por_referencia: 1.5,
      cho_g_por_referencia: 1.3,
      lip_g_por_referencia: 6.9,
      fibra_g_por_referencia: 0.8,
      sodio_mg_por_referencia: 0,
      keywords: ['castanha', 'selênio', 'antioxidante'],
      tipo_refeicao_sugerida: ['morning_snack', 'afternoon_snack'],
      descricao_curta: 'Castanha-do-pará',
      preparo_sugerido: 'In natura',
      popularidade: 85,
      fonte: 'TACO',
      ativo: true
    },
    {
      nome: 'Amêndoas',
      categoria: 'Oleaginosas',
      subcategoria: 'Castanhas',
      peso_referencia_g: 30,
      medida_padrao_referencia: '15 unidades',
      kcal_por_referencia: 174,
      ptn_g_por_referencia: 6.5,
      cho_g_por_referencia: 5.3,
      lip_g_por_referencia: 15.1,
      fibra_g_por_referencia: 3.7,
      sodio_mg_por_referencia: 0,
      keywords: ['amêndoa', 'vitamina E', 'gordura boa'],
      tipo_refeicao_sugerida: ['morning_snack', 'afternoon_snack'],
      descricao_curta: 'Amêndoas torradas',
      preparo_sugerido: 'Torradas',
      popularidade: 80,
      fonte: 'TACO',
      ativo: true
    },
    {
      nome: 'Nozes',
      categoria: 'Oleaginosas',
      subcategoria: 'Castanhas',
      peso_referencia_g: 30,
      medida_padrao_referencia: '7 unidades',
      kcal_por_referencia: 195,
      ptn_g_por_referencia: 4.4,
      cho_g_por_referencia: 4.1,
      lip_g_por_referencia: 19.3,
      fibra_g_por_referencia: 2.0,
      sodio_mg_por_referencia: 1,
      keywords: ['nozes', 'ômega 3', 'cérebro'],
      tipo_refeicao_sugerida: ['morning_snack', 'afternoon_snack'],
      descricao_curta: 'Nozes',
      preparo_sugerido: 'In natura',
      popularidade: 75,
      fonte: 'TACO',
      ativo: true
    },
    {
      nome: 'Amendoim torrado',
      categoria: 'Oleaginosas',
      subcategoria: 'Leguminosas oleaginosas',
      peso_referencia_g: 30,
      medida_padrao_referencia: '2 colheres de sopa',
      kcal_por_referencia: 176,
      ptn_g_por_referencia: 8.1,
      cho_g_por_referencia: 5.7,
      lip_g_por_referencia: 14.5,
      fibra_g_por_referencia: 2.4,
      sodio_mg_por_referencia: 0,
      keywords: ['amendoim', 'proteína', 'energia'],
      tipo_refeicao_sugerida: ['morning_snack', 'afternoon_snack'],
      descricao_curta: 'Amendoim torrado sem sal',
      preparo_sugerido: 'Torrado',
      popularidade: 85,
      fonte: 'TACO',
      ativo: true
    },
    {
      nome: 'Linhaça dourada',
      categoria: 'Oleaginosas',
      subcategoria: 'Sementes',
      peso_referencia_g: 10,
      medida_padrao_referencia: '1 colher de sopa',
      kcal_por_referencia: 50,
      ptn_g_por_referencia: 1.8,
      cho_g_por_referencia: 2.9,
      lip_g_por_referencia: 4.1,
      fibra_g_por_referencia: 2.7,
      sodio_mg_por_referencia: 3,
      keywords: ['linhaça', 'ômega 3', 'fibra'],
      tipo_refeicao_sugerida: ['breakfast', 'afternoon_snack'],
      descricao_curta: 'Linhaça dourada',
      preparo_sugerido: 'Triturada ou moída',
      popularidade: 80,
      fonte: 'TACO',
      ativo: true
    },
    {
      nome: 'Chia',
      categoria: 'Oleaginosas',
      subcategoria: 'Sementes',
      peso_referencia_g: 10,
      medida_padrao_referencia: '1 colher de sopa',
      kcal_por_referencia: 49,
      ptn_g_por_referencia: 1.7,
      cho_g_por_referencia: 4.2,
      lip_g_por_referencia: 3.1,
      fibra_g_por_referencia: 3.4,
      sodio_mg_por_referencia: 2,
      keywords: ['chia', 'ômega 3', 'fibra', 'superalimento'],
      tipo_refeicao_sugerida: ['breakfast', 'afternoon_snack'],
      descricao_curta: 'Semente de chia',
      preparo_sugerido: 'Pode hidratar ou consumir seco',
      popularidade: 85,
      fonte: 'TACO',
      ativo: true
    }
  ];
}

// Exportar todos os alimentos
export function seedAllFoods(): AlimentoV2Insert[] {
  return [
    ...seedTacoCereals(),
    ...seedTacoLegumes(),
    ...seedTacoVegetables(),
    ...seedTacoFruits(),
    ...seedTacoProteins(),
    ...seedTacoDairy(),
    ...seedTacoFatsOils(),
    ...seedTacoNutsSeeds()
  ];
}
